; --- IR dump generated by similang debug ---
; ModuleID = "main"
target triple = "unknown-unknown-unknown"
target datalayout = ""

declare i32 @"printf"(i8* %".1", ...)

@"true" = internal constant i1 1
@"false" = internal constant i1 0
define i32 @"main"()
{
main_entry:
  %".2" = alloca [5 x i32]
  %".3" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 0
  store i32 1, i32* %".3"
  %".5" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 1
  store i32 2, i32* %".5"
  %".7" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 2
  store i32 3, i32* %".7"
  %".9" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 3
  store i32 4, i32* %".9"
  %".11" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 4
  store i32 5, i32* %".11"
  %".13" = alloca i32
  %".14" = alloca i32
  br label %"for_entry"
for_entry:
  %".16" = load i32, i32* %".14"
  %".17" = icmp slt i32 %".16", 5
  br i1 %".17", label %"for_body", label %"for_after"
for_body:
  %".19" = bitcast [9 x i8]* @"__str_const_2577017624" to i8*
  %".20" = load i32, i32* %".14"
  %".21" = getelementptr [5 x i32], [5 x i32]* %".2", i32 0, i32 %".20"
  %".22" = load i32, i32* %".21"
  %".23" = call i32 (i8*, ...) @"printf"(i8* %".19", i32 %".22")
  %".24" = load i32, i32* %".14"
  %".25" = add i32 %".24", 1
  store i32 %".25", i32* %".14"
  br label %"for_entry"
for_after:
  %".28" = load i32, i32* %".13"
  ret i32 %".28"
}

@"__str_const_2577017624" = internal constant [9 x i8] c"arr[%d]\0a\00"