; --- IR dump generated by similang debug ---
; ModuleID = "main"
target triple = "unknown-unknown-unknown"
target datalayout = ""

declare i32 @"printf"(i8* %".1", ...)

@"true" = internal constant i1 1
@"false" = internal constant i1 0
define i32 @"main"()
{
main_entry:
  %".2" = alloca i32
  store i32 40, i32* %".2"
  %".4" = alloca i32
  store i32 2, i32* %".4"
  %".6" = load i32, i32* %".2"
  %".7" = load i32, i32* %".4"
  %".8" = add i32 %".6", %".7"
  ret i32 %".8"
}
